Repository ES2-UFPI/Trabalho-Final-Comput3iros, pull requests merged in 2019-06, with the labels that each got.

#22 Criado a classe Artigo e todas as classes foram movidas para src/
  src/Artigo.java
  src/Configuracao.java
  src/Exemplar.java
  src/Livro.java
  src/Locatario.java
  src/Main.java
Labels: Function

#24 Criado a classe Emprestimo by Lucas Vinicius
  src/Emprestimo.java
Labels: Function

#27 Integracao continua
  .travis.yml
  build.xml
  junit.jar
  org.hamcrest.core_1.3.0.v20180420-1519.jar
  pom.xml
  src/Testes.java
  src/test/java/Testes.java
Labels: Bug fix

#32 Issue#30 hilderlan
  .classpath
  .project
  .settings/org.eclipse.jdt.apt.core.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.m2e.core.prefs
  src/Emprestimo.java
  src/MenuPrincipal.java
  src/SubMenuCadastro.java
  target/classes/Artigo.class
  target/classes/Configuracao.class
  target/classes/Emprestimo.class
  target/classes/Exemplar.class
  target/classes/Livro.class
  target/classes/Locadora.class
  target/classes/Locatario.class
  target/classes/Main.class
  target/classes/MenuPrincipal.class
  target/classes/SubMenuCadastro.class
  target/classes/test/java/Testes.class
Labels: Function

#35 Teste hil
  .classpath
  src/TestesCompletos/TesteLocatario.java
  src/functions/Artigo.java
  src/functions/Configuracao.java
  src/functions/Emprestimo.java
  src/functions/Exemplar.java
  src/functions/Livro.java
  src/functions/Locadora.java
  src/functions/Locatario.java
  src/functions/Main.java
  src/functions/MenuPrincipal.java
  src/functions/SubMenuCadastro.java
  src/test/java/Testes.java
Labels: Bug fix

#36 Issue#9
  src/functions/Emprestimo.java
  src/functions/Locadora.java
Labels: Function

#45 Issue#7 hilderlan lucas v
  src/Locadora.java
  src/Locatario.java
  src/Main.java
  src/MenuPrincipal.java
  src/SubMenuCadastro.java
  src/SubMenuConfiguracao.java
  src/SubMenuExemplar.java
Labels: Function

#48 Issue#11 hilderlan lucas v
  src/Emprestimo.java
  src/Locadora.java
  src/MenuPrincipal.java
Labels: Function

#52 Issue#29 hilderlan lucas v
  src/Locadora.java
  src/MenuPrincipal.java
  src/SubMenuCadastro.java
  src/SubMenuExemplar.java
  src/SubMenuRelatorio.java
Labels: Function

#53 Issue#50 mtb
  src/Emprestimo.java
  src/Livro.java
  src/Locadora.java
  src/MenuPrincipal.java
Labels: Bug fix

#54 Issue#13 pedro
  src/Configuracao.java
  src/Locadora.java
  src/MenuPrincipal.java
  src/SubMenuCadastro.java
  src/SubMenuConfiguracao.java
  src/SubMenuRelatorio.java
Labels: Function

#57 Teste mtb com incrementos no sistema
  src/TestesCompletos/TesteDevolucao.java
Labels: Bug fix

#58 Hil e LucasV - Bastante melhorias no sistema
  src/Locadora.java
  src/MenuPrincipal.java
  src/SubMenuPesquisar.java
Labels: Bug fix

#59 Bug Travis CI fixed
  .project
  src/TestesCompletos/TesteEmprestimo.java
Labels: Bug fix

#60 Finalização do sistema
  .classpath
  .project
  .travis.yml
  README.md
  pom.xml
  src/Artigo.java
  src/Configuracao.java
  src/Emprestimo.java
  src/Exemplar.java
  src/Livro.java
  src/Locadora.java
  src/Locatario.java
  src/Main.java
  src/MenuPrincipal.java
  src/SubMenuCadastro.java
  src/SubMenuConfiguracao.java
  src/SubMenuExemplar.java
  src/SubMenuPesquisar.java
  src/SubMenuRelatorio.java
  src/TestesCompletos/TesteConfiguracao.java
  src/TestesCompletos/TesteDevolucao.java
  src/TestesCompletos/TesteEmprestimo.java
  src/TestesCompletos/TesteExemplar.java
  src/TestesCompletos/TesteLocatario.java
  src/TestesCompletos/TesteMulta.java
  src/test/java/Testes.java
  target/classes/Artigo.class
  target/classes/Configuracao.class
  target/classes/Emprestimo.class
  target/classes/Exemplar.class
  target/classes/Livro.class
  target/classes/Locadora.class
  target/classes/Locatario.class
  target/classes/Main.class
  target/classes/MenuPrincipal.class
  target/classes/SubMenuCadastro.class
  target/classes/test/java/Testes.class
Labels: documentation
